/**
 * Bundles each MCP App view into one self-contained HTML (ADR-036) and writes
 * src/lib/mcp/views/generated.ts. Run with `bun run build:mcp-views` after touching src/mcp-views.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { VIEWS, viewDir, viewSourceHash } from './mcp-views'

// Only the slice of Bun's API this script uses; the repo does not ship @types/bun.
declare const Bun: {
  build(options: { entrypoints: string[]; target: 'browser'; format: 'esm'; minify: boolean }): Promise<{
    success: boolean
    logs: unknown[]
    outputs: { text(): Promise<string> }[]
  }>
}

const out: Record<string, { html: string; sourceHash: string }> = {}

for (const name of VIEWS) {
  const result = await Bun.build({ entrypoints: [join(viewDir(name), 'main.ts')], target: 'browser', format: 'esm', minify: true })
  if (!result.success) {
    console.error(result.logs)
    process.exit(1)
  }
  // An inline module cannot contain a literal closing script tag.
  const js = (await result.outputs[0].text()).replace(/<\/script/gi, '<\\/script')
  const css = readFileSync(join(viewDir(name), 'styles.css'), 'utf8')
  const html = `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>${css}</style></head><body><main id="app"></main><script type="module">${js}</script></body></html>`
  out[name] = { html, sourceHash: viewSourceHash(name) }
  console.log(`${name}: ${(html.length / 1024).toFixed(1)} KB`)
}

const file = `// Generated by scripts/build-mcp-views.ts — do not edit; tests/mcp/views.test.ts checks it is fresh.\n\nexport const MCP_VIEWS = ${JSON.stringify(out)} as const\n`
writeFileSync(join(process.cwd(), 'src/lib/mcp/views/generated.ts'), file)
